version: "2"
services:
  tcp-mocker-app:
    image: tcpmocker/tcp-mocker-app:${TCP_MOCKER_APP_TAG}
    environment:
      - LOGGING_LEVEL_IO_PAYWORKS_LABS_TCPMOCKER=TRACE
    volumes:
      - ./tcp-mappings:/var/lib/tcp-mocker/tcp-mappings
